# Generated by Django 5.0.4 on 2024-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('source_name', models.CharField(max_length=100)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sentiment_comparative', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('sentiment_classification', models.CharField(default='neutral', max_length=50)),
            ],
        ),
    ]
